import type { Metadata } from "next";
import "./globals.css";
import FloatingMusic from "@/components/FloatingMusic";
import GravityCursor from "@/components/gravity-cursor";
import PixelTrail from "@/components/fancy/pixel-trail";
import { mixReg } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mixReg.className} antialiased dark`}>
        {children}
        <div className="absolute top-0 w-full h-screen z-[-10] overflow-hidden">
          <FloatingMusic />
        </div>
        <div className="absolute top-0 w-full h-screen z-[-10] overflow-hidden">
          <GravityCursor />
        </div>
        <div className="fixed top-0 w-full h-screen overflow-hidden">
          <PixelTrail
            pixelSize={20}
            delay={130}
            fadeDuration={0}
            pixelClassName="bg-[#1ed760]"
          />
        </div>
      </body>
    </html>
  );
}
